/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.41
 * Generated at: 2017-03-10 12:55:38 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/spring-webmvc-4.3.3.RELEASE.jar", Long.valueOf(1477046538000L));
    _jspx_dependants.put("jar:file:/home/bridgeit/Desktop/IPL/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/IPL/WEB-INF/lib/spring-webmvc-4.3.3.RELEASE.jar!/META-INF/spring.tld", Long.valueOf(1474276970000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fspring_005furl_0026_005fvar_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fspring_005furl_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fspring_005furl_0026_005fvar_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("    \n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\n");
      out.write("\n");
      out.write("\t<title>IPLT20.com</title>\n");
      out.write("\t<link rel=\"icon\" href=\"images/icon.jpg\" />\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"styles.css\" />\n");
      out.write("\t");
      if (_jspx_meth_spring_005furl_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\t\n");
      out.write("\t<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mainCss}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" rel=\"stylesheet\"/>\n");
      out.write("<style type=\"text/css\">\n");
      out.write("</style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!-- <span style=\"font-size:50px;cursor:pointer\" onclick=\"openNav()\">&#9776; <font color=\"white\">Menu</font></span>\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("\tfunction openNav() {\n");
      out.write("    document.getElementById(\"mySidenav\").style.width = \"250px\";\n");
      out.write("}\n");
      out.write("\n");
      out.write("function closeNav() {\n");
      out.write("    document.getElementById(\"mySidenav\").style.width = \"0\";\n");
      out.write("}\n");
      out.write("</script> -->\t\n");
      out.write("     \n");
      out.write("\n");
      out.write("<body background=\"images/Melbourne-Cricket-Ground-01.jpg\">\n");
      out.write("\n");
      out.write("\t<section id=\"page\"> <!-- Defining the #page section with the section tag -->\n");
      out.write("\n");
      out.write("\t<header> <!-- Defining the header section of the page with the appropriate tag -->\n");
      out.write("\n");
      out.write("\t<a href=\"index.jsp\"><img src=\"images/iplLogo.jpg\"  alt=\"logo\" width=\"400px\" height=\"150\" /></a>\n");
      out.write("\t\t\n");
      out.write("<!-- \n");
      out.write("\t\t/* <nav class=\"clear\"> The nav link semantically marks your main site navigation\n");
      out.write("\n");
      out.write("\t\t\t<ul>\n");
      out.write("\n");
      out.write("\t\t\t\t<li><a href=\"index.jsp\">Home</a></li> \n");
      out.write("\t\t\t\t<li><a href=\"about\">About</a> </li>\n");
      out.write("\t\t\t\t<li><a href=\"signin\">Sign In</a></li>\n");
      out.write("\t\t\t\t<li><a href=\"contact\">Contact</a> </li>\n");
      out.write("\t\t\t\t<li><a href=\"signup\">Sign Up</a></li>\n");
      out.write("\t\t\t\t<li><a href=\"newAddTeam\">Add New Team</a></li>\n");
      out.write("\t\t\t\t<li><a href=\"newAddPlayer\">Add New Player</a></</font>li>\n");
      out.write("\n");
      out.write("\t\t\t</ul>\n");
      out.write("\n");
      out.write("\t\t</nav> */ -->\n");
      out.write("\t\t\n");
      out.write("\t\t<!-- <div id=\"mySidenav\" class=\"sidenav\">\n");
      out.write("\t\t  <a href=\"javascript:void(0)\" class=\"closebtn\" onclick=\"closeNav()\">&times;</a>\n");
      out.write("\t\t  <a href=\"about\">About</a>\n");
      out.write("\t\t  <a href=\"signin\">SignIn</a>\n");
      out.write("\t\t  <a href=\"contact\">Contact</a>\n");
      out.write("\t\t  <a href=\"index.jsp\">Home</a>\n");
      out.write("\t\t</div> -->\n");
      out.write("\t\t\n");
      out.write("<div id=\"mySidenav\" class=\"sidenav\">\n");
      out.write("  <a href=\"about\" id=\"about\">About</a>\n");
      out.write("  <a href=\"signin\" id=\"signin\">SignIn</a>\n");
      out.write("  <a href=\"signup\" id=\"signup\">SignUp</a>\n");
      out.write("  <a href=\"contact\" id=\"contact\">Contact</a>\n");
      out.write("\n");
      out.write("</div>\n");
      out.write("<a href=\"newAddTeam\">Add New Team</a>\n");
      out.write("\t\t\t\t<a href=\"newAddPlayer\">Add New Player</a>\n");
      out.write(" <!--  <a href=\"mypage.jsp\">Page</a> -->\n");
      out.write("\n");
      out.write("\t</header>\n");
      out.write("\t\n");
      out.write("\t<div class=\"line\"></div>  <!-- Dividing line -->\n");
      out.write("\n");
      out.write("\t<article id=\"article1\"> <!-- The new article tag. The id is supplied so it can be scrolled into view. -->\n");
      out.write("\n");
      out.write("\t\t<h2>IPL Season 2017</h2>\n");
      out.write("\n");
      out.write("\t\t<div class=\"line\"></div>\n");
      out.write("\n");
      out.write("\t\t<div class=\"articleBody clear\">\n");
      out.write("\n");
      out.write("\t\t\t<figure> <!-- The figure tag marks data (usually an image) that is part of the article -->\n");
      out.write("\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t\t\t<img src=\"images/iplimage.jpg\" width=\"750\" height=\"500\" alt=\"img not found\"/>\n");
      out.write("\n");
      out.write("\t\t\t</figure>\n");
      out.write("\n");
      out.write("\t\t\t<p><font color=\"white\">The 2017 season of the Indian Premier League, also known as IPL 10\n");
      out.write("\t\t\twill be the tenth season of the IPL, a professional Twenty20 cricket\n");
      out.write("\t\t\tleague established by the Board of Control for Cricket in India (BCCI)\n");
      out.write("\t\t\tin 2007. The tournament will feature the eight teams that played in the\n");
      out.write("\t\t\tprevious season. The 2017 season is scheduled to start on 5 April 2017 \n");
      out.write("\t\t\tand finish on 21 May 2017, with Hyderabad hosting the opening match and\n");
      out.write("\t\t\tthe final</font></p>\n");
      out.write("\n");
      out.write("\t\t\t\n");
      out.write("\n");
      out.write("\t\t</div>\n");
      out.write("\n");
      out.write("\t</article>\n");
      out.write("\t<footer> \n");
      out.write("\n");
      out.write("\t\t\t<div class=\"line\"></div>\n");
      out.write("\n");
      out.write("\t\t\t<p>&copy; Vivo IPL 2017 Schedule. All Rights Reserved.</p> <!-- Change the copyright notice -->\n");
      out.write("\t\t\t<a href=\"#\" class=\"up\"><input type= \"button\" value=\"Go Up\"></a>\n");
      out.write("\t\t\t\n");
      out.write("\n");
      out.write("\t\t</footer>\n");
      out.write("\n");
      out.write("\t</section> <!-- Closing the #page section -->\n");
      out.write("\n");
      out.write("\t<!-- JavaScript Includes -->\n");
      out.write("\n");
      out.write("\t<script src=\"http://ajax.googleapis.com/ajax/libs/jquery/1.3.2/jquery.min.js\"></script>\n");
      out.write("\t<script src=\"jquery.scrollTo-1.4.2/jquery.scrollTo-min.js\"></script>\n");
      out.write("\t<script src=\"script.js\"></script>\n");
      out.write("\n");
      out.write("\t</body>\n");
      out.write("\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_spring_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:url
    org.springframework.web.servlet.tags.UrlTag _jspx_th_spring_005furl_005f0 = (org.springframework.web.servlet.tags.UrlTag) _005fjspx_005ftagPool_005fspring_005furl_0026_005fvar_005fvalue_005fnobody.get(org.springframework.web.servlet.tags.UrlTag.class);
    boolean _jspx_th_spring_005furl_005f0_reused = false;
    try {
      _jspx_th_spring_005furl_005f0.setPageContext(_jspx_page_context);
      _jspx_th_spring_005furl_005f0.setParent(null);
      // /index.jsp(11,1) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005furl_005f0.setValue("/CSS/IPl.css");
      // /index.jsp(11,1) name = var type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spring_005furl_005f0.setVar("mainCss");
      int[] _jspx_push_body_count_spring_005furl_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_spring_005furl_005f0 = _jspx_th_spring_005furl_005f0.doStartTag();
        if (_jspx_th_spring_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spring_005furl_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spring_005furl_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spring_005furl_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fspring_005furl_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_spring_005furl_005f0);
      _jspx_th_spring_005furl_005f0_reused = true;
    } finally {
      if (!_jspx_th_spring_005furl_005f0_reused) {
        _jspx_th_spring_005furl_005f0.release();
        _jsp_getInstanceManager().destroyInstance(_jspx_th_spring_005furl_005f0);
      }
    }
    return false;
  }
}
